### ISSUE TITLE
Need to add functionality for pulling the results of matches

### ISSUE THREAD

**Issue by MichaelClarkFsu** [KPCOFGS/BetBuddy#44]
We can use TheOdds api to get the results of the matches after they conclude.

**Comment by KPCOFGS** [comment]
The Odd API does not support historical data, and getting game scores can only go as far as 3 days before. We will be calculating the probability by using the formula 100/(Odds+100) for positive odds and -Odds/(-Odds+100) for negative odds. Assign the probability to each team and then randomly select the winning team according to the calculated probability

**Comment by MichaelClarkFsu** [comment]
While we can't pull historical odds we should still be able to pull the scores for all the matches and get the actual result instead of using the probabilities to make a random selection.

**Comment by KPCOFGS** [comment]
Yes, but it is only allowed up to 3 days before the current day. If the user logs into their account 4 days after the games being concluded, some results cannot be fetched

**Comment by KPCOFGS** [comment]
You can test it using the following link provided on [TheOddAPI page](https://the-odds-api.com/liveapi/guides/v4/#parameters-3):
https://api.the-odds-api.com/v4/sports/americanfootball_nfl/scores/?daysFrom={day}&apiKey={YOUR_API_KEY}

**Comment by MichaelClarkFsu** [comment]
Ah I see. So we make a disclaimer about that issue to users and still pull scores anyway or would it cause too many problems?
Like we can put a note that all bets must be cashed in within 3 days?

**Comment by KPCOFGS** [comment]
Sure I think that would work

**Comment by KPCOFGS** [comment]
Strangely, when checking for game scores, Seahawks versus Packers gets updated to the next week's game, and this week's score is no longer accessible even it's still within 3 days range:
https://api.the-odds-api.com/v4/sports/americanfootball_nfl/scores/?daysFrom3=1&apiKey=676dad172b631f7293525e96e1ec921b

**Comment by KPCOFGS** [comment]
Done
