### ISSUE TITLE
Add functionality where a user can claim a daily amount of free tokens for them to place a bet with

### ISSUE THREAD

**Issue by MichaelClarkFsu** [KPCOFGS/BetBuddy#47]
Users should be able to claim a pre-specified amount of tokens daily to place bets with. This can be done using a claim daily tokens button of some sort on the user page.

**Comment by KPCOFGS** [comment]
Once the user logs in, if the day is different from when daily reward has been claimed, the user will then recieve daily reward (500 virtual currency) and sets the new claim date to that day.
