### ISSUE TITLE
A disclaimer somewhere

### ISSUE THREAD

**Issue by KPCOFGS** [KPCOFGS/BetBuddy#54]
A disclaimer page somehwere to let users know they need to get the money out after the game concludes. Virtual money will be gone after 3 days due to the api limit

**Comment by ChristianAR39** [comment]
Do you have a preferred location where users should access this page from?

**Comment by KPCOFGS** [comment]
IT could be some place in ther user.html, or at the login screen

**Comment by 7JP10** [comment]
Modifications made:

<img width="1236" alt="Screenshot 2024-12-09 at 11 19 02 PM" src="https://github.com/user-attachments/assets/b1d92ab0-7b53-4ddc-8ecf-e4208fa2e7c8">
