### ISSUE TITLE
Make templates look uniform across app 

### ISSUE THREAD

**Issue by 7JP10** [KPCOFGS/BetBuddy#58]
I will be working on the templates to make sure that all the templates look uniform across the platform.

**Comment by KPCOFGS** [comment]
Which ones are you working on? I see the pages are pretty consistent already

**Comment by 7JP10** [comment]
- Log in page (color scheme)
- Sign up page (color scheme)
- User Home Screen (color scheme)

<img width="1236" alt="Screenshot 2024-12-07 at 10 36 36 PM" src="https://github.
<img width="1236" alt="Screenshot 2024-12-07 at 10 41 55 PM" src="https://github.com/user-attachments/assets/9c0754ae-6003-45c2-9de2-5324b54e3c49">
com/user-attachments/assets/5bce11de-b70e-492c-9c44-71091599088d">
<img width="1236" alt="Screenshot 2024-12-07 at 10 36 13 PM" src="https://github.com/user-attachments/assets/4ac61347-ad57-406a-b068-1ea03abbdad7">

**Comment by 7JP10** [comment]
Made the changes:

<img width="1236" alt="Screenshot 2024-12-09 at 11 24 08 PM" src="https://github.com/user-attachments/assets/0a8fb305-0c31-48dd-9d1d-3cbbc4c27e58">
<img width="1236" alt="Screenshot 2024-12-09 at 11 24 28 PM" src="https://github.com/user-attachments/assets/cffd151b-0b06-4da5-b9c8-4b8da7d44d35">
